import Footer from '@/components/Footer/Footer'
import Header from '@/components/Header/Header'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'BlockChains',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div
					className='fixed 
					z-[999]
					bottom-[10px] bg-sky-500  h-[30px] w-[70px] rounded border border-black/[.3] left-[5px]'
				>
					<div className='h-full w-full text-sm text-white font-bold flex items-center justify-center  after:absolute after:content-["xs"] sm:after:content-["sm"] md:after:content-["md"] lg:after:content-["lg"] xl:after:content-["xl"] 2xl:after:content-["2xl"] '></div>
				</div>
				<Header />
				<div className='mt-24 mb-24 min-h-[70vh]'>{children}</div>
				<Footer />
			</body>
		</html>
	)
}
